### ISSUE TITLE
mybookingsherpa.com domain path

### ISSUE THREAD

**Issue by stevepetebruce** [AlanDonohoe/mybookingsherpa-marketingpage#8]
https://mybookingsherpa.com/ works great.

https://www.mybookingsherpa.com/ displaying 404.
Message: The specified bucket does not exist

<img width="828" alt="Screenshot 2019-03-14 at 17 31 22" src="https://user-images.githubusercontent.com/2472713/54378361-0fb7b780-467f-11e9-9a8a-2eb3bd75eee3.png">

**Comment by AlanDonohoe** [comment]
This works now
